### ISSUE TITLE
ESP32 with SSD1963

### ISSUE THREAD

**Issue by harvey2206** [gnulabis/UTFT-ESP8266#28]
Hello,

Does this driver supports run SSD1963 (800x480, 5inch TFT) chip based display with ESP32 (over SPI) ? 

Best Regards 
Harvey

**Comment by gnulabis** [comment]
Not sure, this project provides ESP support for the upstream UTFT.

To check if your module is supported, have a look at the upstream documentation:
https://github.com/gnulabis/UTFT-ESP/raw/master/UTFT/Documentation/UTFT_Supported_display_modules_%26_controllers.pdf

If UTFT supports it using a serial interface, then yes, it will work. Otherwise, if you can add support for your module yourself, you should contribute your patch upstream, not here.

Cheers.
